### ISSUE TITLE
Add an option for set the number of packets sent per unit of time

### ISSUE THREAD

**Issue by Payne-X6** [thewhoo/dpdk-tcp-generator#3]
Right now is possible to set pace of sending using parameter `-t` but number of packets will act differ on different hardware. It seems more useful to define the maximum number of packets sent per unit of time (eg. per second)

**Comment by thewhoo** [comment]
I agree. Parameter `-t` has been completely removed and replaced with parameter `-g` which can be used to set the minimum microsecond delay between opening new TCP connections.
